return {
    Owner = {
        displayName = "Owner",
        color = Color3.fromRGB(255, 215, 0),
        priority = 1
    },
    Admin = {
        displayName = "Administrador",
        color = Color3.fromRGB(255, 0, 0),
        priority = 2
    },
    Moderator = {
        displayName = "Moderador", 
        color = Color3.fromRGB(0, 255, 0),
        priority = 3
    },
    Vip = {
        displayName = "VIP",
        color = Color3.fromRGB(255, 255, 0),
        priority = 4
    }
}
